### ISSUE TITLE
Switching meeting roles each check-in

### ISSUE THREAD

**Issue by sstevens2** [tobyhodges/lesson-sprint-recommendations#17]
> To further promote equity of participation, these roles should be rotated for each check-in call

I'm feeling like maybe this could be recommended between each sprint?  I found it hard to rotate these between each check-in as it felt a bit like increased cognitive load. Between sprints would give participants more time to practice the role a bit.

In either case, I think it would be good to recommend the lead organizer write down who is taking which role for each break/day and then remind the group of the roles they are assigned anytime you switch.

**Comment by tobyhodges** [comment]
I think this is a good point, especially about recommending the lead organiser to note down the roles. Would you like to make a PR to address this, @sstevens2? If you don't have time I will do so in the next week or two.
