### ISSUE TITLE
Some comments on recommendations

### ISSUE THREAD

**Issue by SarahAlidoost** [tobyhodges/lesson-sprint-recommendations#22]
Thank you for creating the recommendation document, nice work everyone. Here my comments separated on each section in the readme, hope that it helps:

1- [Planning your lesson](https://github.com/tobyhodges/lesson-sprint-recommendations/blob/main/lesson_planning.md):

- The section “Planning your lesson” contains some tasks that need to be done before the sprint. Also, some of the items in this file are already mentioned in the section “[Recommendations for what to do before a lesson sprint](https://github.com/tobyhodges/lesson-sprint-recommendations/blob/main/before.md)”.  I suggest merging these two sections. This makes the text less redundant and the document better organized. 
- The title “[Planning a lesson checklist](https://github.com/tobyhodges/lesson-sprint-recommendations/blob/main/lesson_planning.md#planning-a-lesson-checklist)” is not clear. I suggest changing to: “Planning a lesson development sprint”.
- In this part of the text, `Refer to sections of the Instructor Training Curriculum and Teaching Tech Together on learning objectives on how to develop them effectively.`, it seems that the links are not inserted.  
- I suggest adding a reference to [Lesson life cycle](https://cdh.carpentries.org/the-lesson-life-cycle.html) because it helps the organizer in planning. 

2- [Recommendations for what to do before a lesson sprint](https://github.com/tobyhodges/lesson-sprint-recommendations/blob/main/before.md):

- The items mentioned in this file can be done by the organizer committee **before** the development sprint **except** the items `Run a "sprint primer" session` and `a skill-up session for contributors`. In my opinion, these two sessions are actually parts of the development sprint and done by contributors. However, I understand that the organizer should plan these two sessions beforehand. This can be mentioned under the item `List of prerequisite skills for the lesson`.

3- [Recommendations for what to do after a lesson sprint](https://github.com/tobyhodges/lesson-sprint-recommendations/blob/main/after.md):

- The items mentioned in this file can be done by the organizer committee **after** the development sprint **except** for the items `Complete any remaining reviews` and` Review open Pull Requests`. These two sessions are actually parts of the development sprint and done by contributors. 

4- [Recommended tools that may help you when planning and running a lesson sprint](https://github.com/tobyhodges/lesson-sprint-recommendations/blob/main/tools.md):
I suggest using [Gitter](https://gitter.im/) as well. 

5- Also, I found some typos that are mentioned as **bold** words here:

- `README.md`: Recommended tools that may help you when planning and **runnning** a lesson sprint
- `after.md`: Consider turning this overview into a blog post to share **you** experience and achievements with the wider community!
- `before.md`: If you have more than 2-3 people, be sure to assign roles to avoid diffusion of **reponsbility**.
- `during.md`: across **mutliple** sessions/days and/or a wide range of timezones.
- `during.md`: You might consider providing guidance/assigning **responsibilty** for reviewers.
- `tools.md`: provides a cloud-based development **environments** for projects.

**Comment by tobyhodges** [comment]
@libcce was +1 on adding Gitter to the tool list too.

**Comment by tobyhodges** [comment]
Thanks so much for this detailed review @SarahAlidoost! It was extremely helpful. I have addressed your points with #37
